output "s3_bucket_name" {
  value       = aws_s3_bucket.website_bucket.id
  description = "The name of the S3 bucket where assets are hosted."
}

output "cloudfront_domain_name" {
  value       = aws_cloudfront_distribution.cdn.domain_name
  description = "The default domain name generated by CloudFront."
}

output "cloudfront_distribution_id" {
  value       = aws_cloudfront_distribution.cdn.id
  description = "The CloudFront distribution ID."
}
